apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  labels:
    app: kafka
    tier: middleware
spec:
  ports:
  - port: 9092
    protocol: TCP
    name: kafka-broker-port
  - port: 7203
    protocol: TCP
    name: kafka-jmx-port
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: zk-svc
  labels:
    app: zk
    tier: middleware
spec:
  ports:
  - port: 2181
    protocol: TCP
    name: zk-port
  selector:
    app: zookeeper
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kafka
    spec:
      volumes:
        - name: kafka-data-vol
          emptyDir: {}
        - name: kafka-logs-vol
          emptyDir: {}
        - name: nobrokerid-kafka-configmap
          configMap:
            name: nobrokerid-kafka
      containers:
      - name: kafka
        image: ches/kafka:0.10.1.0
        env:
          - name: ZOOKEEPER_CONNECTION_STRING
            value: $(ZK_SVC_SERVICE_HOST):$(ZK_SVC_SERVICE_PORT)
        ports:
        - containerPort: 9092
        - containerPort: 7203
        volumeMounts:
          - mountPath: /data
            name: kafka-data-vol
          - mountPath: /logs
            name: kafka-logs-vol
          - mountPath: /kafka/config
            name: nobrokerid-kafka-configmap
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zk-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
#      volumes:
#        - name: zk-conf-vol
#          emptyDir: {}
#        - name: zk-tmp-vol
#          emptyDir: {}
      containers:
      - name: zookeeper
        image: jplock/zookeeper:3.4.9
        ports:
        - containerPort: 2181
#        volumeMounts:
#          - mountPath: /opt/zookeeper/conf
#            name: zk-conf-vol
#          - mountPath: /tmp/zookeeper
#            name: zk-tmp-vol
