apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace: kafka-ns
  labels:
    app: kafka
    tier: middleware
spec:
  ports:
  - port: 9092
    protocol: TCP
    name: kafka-broker-port
  - port: 7203
    protocol: TCP
    name: kafka-jmx-port
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: zk-svc
  namespace: kafka-ns
  labels:
    app: zk
    tier: middleware
spec:
  ports:
  - port: 2181
    protocol: TCP
    name: zk-port
  selector:
    app: zookeeper
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-deployment
  namespace: kafka-ns
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kafka
    spec:
      volumes:
        - name: kafka-data-vol
          emptyDir: {}
        - name: kafka-logs-vol
          emptyDir: {}
      containers:
      - name: kafka
        image: madchap/docker-kafka
        ports:
        - containerPort: 9092
        - containerPort: 7203
        volumeMounts:
          - mountPath: /data
            name: kafka-data-vol
          - mountPath: /logs
            name: kafka-logs-vol
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zk-deployment
  namespace: kafka-ns
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: jplock/zookeeper:3.4.9
        ports:
        - containerPort: 2181
